version: "2"

services:
  builder:
      privileged: true #this need privilages to run because it needs access to a loop device
      build:
        context: ./env
        dockerfile: Dockerfile
      container_name: pikios_builder
      volumes:
        - ./:/build